
logging:
  level:
    com.atmoon.sharding.mapper: info
spring:
  profiles:
    active: dev
  shardingsphere:
    props:
      sql.show: true # 线上环境需要关闭
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-jdbc?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
        maxActive: 100
        maxWait: 1000
    sharding:
      default-data-source-name: ds0
      tables:
        cart:
          keyGenerator:
            type: SNOWFLAKE
            column: id
          actual-data-nodes: ds0.cart_$->{0..3} #表后缀从0开始这里为0..n-1, 后缀从1开始这里为1..n, n为多少张表,
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds0
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: cart_$->{id.intdiv(1000) % 4} #建议多少张表余多少
  application:
    name: cart-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 开启mybatis-plus全sql 打印，仅可开发测试环境开启
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jarvan.sharding.entity
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      update-strategy: not_null
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0